@PortfolioManagement.Api_HostAddress = http://localhost:5046

POST {{PortfolioManagement.Api_HostAddress}}/auth/login
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "Test123!"
}

###

@token = ey...

POST {{PortfolioManagement.Api_HostAddress}}/api/portfolios
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "My Portfolio2",
  "description": "Test portfolio."
}

###

POST {{PortfolioManagement.Api_HostAddress}}/api/portfolios/2/trades
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": 10,
  "price": 100.00,
  "executedDate": "2026-05-08"
}

###

GET {{PortfolioManagement.Api_HostAddress}}/stocks/AAPL/history?from=2026-01-01&to=2026-01-02&timespan=day
Accept: application/json

###

GET {{PortfolioManagement.Api_HostAddress}}/api/instruments/search?query=apple&limit=10
Accept: application/json


###

@token = ey...
@portfolioId = 3

DELETE {{PortfolioManagement.Api_HostAddress}}/api/portfolios/{{portfolioId}}
Content-Type: application/json
Authorization: Bearer {{token}}

###

@token = ey..

GET {{PortfolioManagement.Api_HostAddress}}/api/portfolios
Accept: application/json
Authorization: Bearer {{token}}
