@PortfolioManagement.Api_HostAddress = http://localhost:5046

POST {{PortfolioManagement.Api_HostAddress}}/api/portfolios
Content-Type: application/json

{
  "name": "My Portfolio",
  "description": "Test portfolio."
}

###

POST {{PortfolioManagement.Api_HostAddress}}/api/portfolios/2/trades
Content-Type: application/json

{
  "symbol": "AAPL",
  "quantity": 10,
  "price": 100.00,
  "executedDate": "2026-05-08"
}

###